apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: topolvm-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
  - kind: ServiceAccount
    name: {{ template "topolvm.fullname" . }}-lvmd
  - kind: ServiceAccount
    name: {{ template "topolvm.fullname" . }}-node
