desiredUpdate:
  image: quay.io/okd/scos-release@sha256:e01396cf9753a998af2a2cbb4897daab7cdd656f1fdfa779019933a180933910

overrides:
  - group: apps
    kind: Deployment
    name: ingress-operator
    namespace: openshift-ingress-operator
    unmanaged: true

kubelet:
  master:
    podPidsLimit: 512
    containerLogMaxSize: 50Mi
    maxPods: 500
    kubeAPIBurst: 256
    kubeAPIQPS: 128
    systemReserved:
      cpu: 2000m
      memory: 2Gi
