desiredUpdate:
  image: quay.io/okd/scos-release@sha256:2237a02fc4d1554e655d3f4f7dd12c56109675dcf0c1189ef937941f8876257f

kubelet:
  master:
    podPidsLimit: 512
    containerLogMaxSize: 50Mi
    maxPods: 500
    kubeAPIBurst: 256
    kubeAPIQPS: 128
