desiredUpdate:
  image: quay.io/okd/scos-release@sha256:e8b568ac8f5bff34ae434c707d2dda2062859ff8cfb1e8a13103a4574644d45c

kubelet:
  master:
    podPidsLimit: 512
    containerLogMaxSize: 50Mi
    maxPods: 500
    kubeAPIBurst: 256
    kubeAPIQPS: 128
