apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: default
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  namespace: openshift-ingress
spec:
  gatewayClassName: openshift-default
  listeners:
  {{- if .Values.redirectHttp }}
  - name: http
    hostname: "*.{{ .Values.listenerWildcardDomain }}"
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  {{- end }}
  - name: https
    hostname: "*.{{ .Values.listenerWildcardDomain }}"
    port: 443
    protocol: HTTPS
    tls:
      mode: Terminate
      certificateRefs:
      - name: gwapi-wildcard
    allowedRoutes:
      namespaces:
        from: All
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: default-gw-options
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-gw-options
  namespace: openshift-ingress
data:
  service: |
    spec:
      loadBalancerIP: {{ .Values.listenerIpAddress }}
---
apiVersion: v1
kind: Service
metadata:
  name: default-openshift-default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  namespace: openshift-ingress
spec:
  loadBalancerIP: {{ .Values.listenerIpAddress }}
