{{- if .Values.redirectHttp }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-filter-redirect
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  namespace: openshift-ingress
spec:
  parentRefs:
  - name: default
    sectionName: http
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
{{- end }}
