---
clusterMonitoringConfig:
  enableUserWorkload: true
  prometheusK8s:
    retention: 168h
    volumeClaimTemplate:
      spec:
        storageClassName: topolvm
        volumeMode: Filesystem
        resources:
          requests:
            storage: 40Gi
userWorkloadMonitoringConfig:
  prometheus:
    retention: 72h
    volumeClaimTemplate:
      spec:
        storageClassName: topolvm
        volumeMode: Filesystem
        resources:
          requests:
            storage: 40Gi
