apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  {{- with .Values.desiredUpdate }}
  desiredUpdate:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.overrides }}
  overrides:
    {{- toYaml . | nindent 4 }}
  {{- end }}
