apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amd-deviceconfig
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    name: in-cluster
    namespace: amd-gpu-operator
  project: default
  source:
    path: charts/amd-deviceconfig
    repoURL: git@github.com:jharmison-redhat/framework-okd.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
