apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: config
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  destination:
    name: in-cluster
    namespace: openshift-config
  project: default
  source:
    path: charts/config
    repoURL: git@github.com:jharmison-redhat/framework-okd.git
    targetRevision: HEAD
    helm:
      valueFiles:
        - ../../clusters/okd.jharmison.dev/values/config/values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
