apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: metallb-operator
spec:
  channel: {{ .Values.channel }}
  installPlanApproval: Automatic
  name: metallb-operator
  source: okderators
  sourceNamespace: openshift-marketplace
